version: '3.8'

services:
  app:
    container_name: app
    image: note_vi_image
    hostname: app
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - app_db
    restart: always

  app_db:
    container_name: app_db
    hostname: app_db
    image: postgres:13.2
    env_file:
      - .env.dev
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"

  redis:
    image: redis:6.2-alpine
    hostname: redis
    env_file:
      - .env.dev
    container_name: redis
    command:
      - 'redis-server'
      # - '--requirepass $REDIS_PASSWORD'
      - '--requirepass myStrongPassword'
    ports:
      - 36379:6379

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: app_main