"""summary

Revision ID: 0b3654e2fae5
Revises: f5848ce1d5be
Create Date: 2024-04-01 13:34:04.889268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b3654e2fae5'
down_revision: Union[str, None] = 'f5848ce1d5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('summary_path', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_summary_author_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summary'))
    )
    op.create_table('summary_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], name=op.f('fk_summary_image_summary_id_summary'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summary_image')),
    sa.UniqueConstraint('path', name=op.f('uq_summary_image_path'))
    )
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('summary_image')
    op.drop_table('summary')
    # ### end Alembic commands ###
