"""fix user_notes

Revision ID: 381d7f304d62
Revises: 961066f81de1
Create Date: 2024-04-12 16:20:52.078968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381d7f304d62'
down_revision: Union[str, None] = '961066f81de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_summary_summary_path'), 'summary', ['summary_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_summary_summary_path'), 'summary', type_='unique')
    # ### end Alembic commands ###
