"""refact favorites

Revision ID: bf4ea2491335
Revises: 381d7f304d62
Create Date: 2024-04-12 16:46:36.226910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4ea2491335'
down_revision: Union[str, None] = '381d7f304d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name=op.f('fk_note_user_note_id_note'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_note_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'note_id', name=op.f('pk_note_user'))
    )
    op.create_table('summary_user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], name=op.f('fk_summary_user_summary_id_summary'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_summary_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'summary_id', name=op.f('pk_summary_user'))
    )
    op.drop_table('favorite_notes')
    op.drop_table('summary_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], name='fk_summary_users_summary_id_summary', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_summary_users_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'summary_id', name='pk_summary_users')
    )
    op.create_table('favorite_notes',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='fk_favorite_notes_note_id_note', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_favorite_notes_user_id_user', ondelete='CASCADE')
    )
    op.drop_table('summary_user')
    op.drop_table('note_user')
    # ### end Alembic commands ###
