"""change

Revision ID: e097fb201c84
Revises: e3de439483fe
Create Date: 2024-03-08 06:09:43.428433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e097fb201c84'
down_revision: Union[str, None] = 'e3de439483fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_tokens_user_id_user', 'user_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_tokens_user_id_user'), 'user_tokens', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_tokens_user_id_user'), 'user_tokens', type_='foreignkey')
    op.create_foreign_key('fk_user_tokens_user_id_user', 'user_tokens', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
