"""notes

Revision ID: f295829871a6
Revises: 0b3654e2fae5
Create Date: 2024-04-03 13:01:40.585584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f295829871a6'
down_revision: Union[str, None] = '0b3654e2fae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('intro', sa.String(length=512), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_note_author_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_table('favorite_notes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name=op.f('fk_favorite_notes_note_id_note'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_notes_user_id_user'), ondelete='CASCADE')
    )
    op.create_table('image_note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name=op.f('fk_image_note_note_id_note'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_note')),
    sa.UniqueConstraint('path', name=op.f('uq_image_note_path'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_note')
    op.drop_table('favorite_notes')
    op.drop_table('note')
    # ### end Alembic commands ###
